# Generated by Django 4.1.2 on 2022-10-08 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import universe_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(max_length=254)),
                ('image', models.ImageField(default='/profile_pics/default/default.jpg', upload_to='profile_pics/default')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=universe_app.models._upload_path)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 23, 59, 41, 829643))),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe_app.profile')),
            ],
        ),
    ]
