# Generated by Django 4.1.1 on 2022-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0002_delete_codes_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/default/profile.png3', upload_to='profile_pics'),
        ),
    ]
