# Generated by Django 4.1.1 on 2022-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/defaul/default.jpg', upload_to='profile_pics'),
        ),
    ]
